### ISSUE TITLE
Repo misnamed?

### ISSUE THREAD

**Issue by rishson** [dojo/cli-css-typings#2]
It should have been pointed out (but wasn't) that the naming conventions for `cli` commands is:

`cli-group-command` e.g. `cli-create-app` or `cli-build-webpack`

Therefore, this repo should really be `cli-build-cssModules` (not sure on the camelcase though).

I'm not sure where to document the convention though as technically we don't care about the repo name, but with lots of commands, it will get confusing if we have no naming convention.

**Comment by rishson** [comment]
Unless the command can be used from multiple groups then maybe loose the `group` part?
e.g.
`cli-cssModules` can be called from `build`, `test`....

**Comment by kitsonk** [comment]
`cli-build-cssmodules`?

**Comment by bitpshr** [comment]
I was thinking we'd offer other CSS-specific commands, such as wrapping Stylus or SASS compilation, so `css` would be the group. E.g. `dojo css modules`, `dojo css stylus`, etc.

If we want to go with `cli-build-cssmodules`, that means the [cli-build](http://github.com/dojo/cli-build) is misnamed also. It should be `cli-build-webpack`.

**Comment by kitsonk** [comment]
It is now `cli-css-typings`
